# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SiriKitTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SiriKitTest
	pod 'Hyphenate', '~> 3.3.7'
end

target 'SiriKitTestIntent' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SiriKitTestIntent
	pod 'Hyphenate', '~> 3.3.7'
end
